Repository bs3265/trainsim-public-group7, pull requests merged in 2021-09, with the labels that each got.

#34 [Payment]: Integrate the trainsim-stripe-service to this project.
  docker-compose.yml
  pom.xml
  trainsim-stripe-service/pom.xml
  trainsim-stripe-service/src/main/java/edu/drexel/trainsim/App.java
  trainsim-stripe-service/src/main/java/edu/drexel/trainsim/models/CreditCardInfo.java
  trainsim-stripe-service/src/main/java/edu/drexel/trainsim/models/PaymentRequest.java
  trainsim-stripe-service/src/main/java/edu/drexel/trainsim/models/PaymentResponse.java
  trainsim-stripe-service/src/main/java/edu/drexel/trainsim/models/PriceRequest.java
  trainsim-stripe-service/src/main/java/edu/drexel/trainsim/models/PriceResponse.java
  trainsim-stripe-service/src/main/java/edu/drexel/trainsim/web/Controller.java
  trainsim-stripe-service/src/main/java/edu/drexel/trainsim/web/PaymentController.java
  trainsim-stripe-service/src/main/java/edu/drexel/trainsim/web/PriceController.java
  trainsim-stripe-service/src/test/java/edu/drexel/trainsim/AppTest.java
Labels: enhancement

#46 Sanity tests
  trainsim-api/src/test/python/__init__.py
  trainsim-api/src/test/python/test_getQuery.py
  trainsim-api/src/test/python/test_getStops.py
  trainsim-api/src/test/python/test_getUser.py
Labels: test cases

#35 add paypal option on checkout
  trainsim-api/pom.xml
  trainsim-api/src/main/app.properties
  trainsim-api/src/main/java/edu/drexel/trainsim/App.java
  trainsim-api/src/main/java/edu/drexel/trainsim/order/ApiPropertyLoader.java
  trainsim-api/src/main/java/edu/drexel/trainsim/order/OptionLoader.java
  trainsim-api/src/main/java/edu/drexel/trainsim/order/PayPalClient.java
  trainsim-api/src/main/java/edu/drexel/trainsim/order/PaypalCreateOrder.java
  trainsim-api/src/main/java/edu/drexel/trainsim/web/PayPalCreateOrderController.java
  trainsim-client/src/components/App.tsx
  trainsim-client/src/components/CheckoutPage.tsx
Labels: enhancement

#47 Sanity tests: readme
  README.md
Labels: documentation
